name: Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Check installation
      run: make install check

    - name: Run tests
      run: mkdir view config && make test
